#!/usr/bin/env bash

#
# List all files tracked by git
#
git ls-tree -r --name-only HEAD | while read filename; do
    echo "$(git log -1 --format="%at | %h | %an | %ad |" -- $filename) $filename"
done
