#!/usr/bin/env bash

# add 'build-jenkins' to the current list of custom commands
export git_custom_commands="${git_custom_commands} build-jenkins"

#
# Launch the gerrit/jenkins build script
#
function git-build-jenkins {
	current_git_project=$(git remote -v | head -n1 | awk '{print $2}' | sed 's/.*\///' | sed 's/\.git//')
	case "$1" in
		# Continuous-integration environment build
		# Test environment build
		# Production environment build
		"ci" | "test" | "prod")
			command ~/.dotfiles/resources/lib/.git-build-jenkins/build.py $1 ${current_git_project}
		;;

		# Default
		*)
			echo "Unknown build target '$1'"
		;;
	esac
}
