#
# Bash aliases
#
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
#alias ls='ls -aF --color=auto'
alias ls='ls -aFG'
alias ll='ls -l'
alias l='ls -1'
alias e='exit'
alias cls='clear'
alias csl='clear'
alias pico='nano'
alias pioc='nano'
alias pcio='nano'
alias pcoi='nano'
alias vi='vim'
alias pioc='pico'
alias more='less'
alias md='mkdir'
alias grep='grep -n --color=auto'
alias top='htop -d 5'
alias suod='sudo'

