#!/usr/bin/env bash

# command wrapper
#   Executes any custom commands found in the ./lib directory and
#   displays an interactive menu for "did you mean" error suggestions.
arg=1
cmd="__ext"
found=0
shift_to=1
tst=$cmd

# search for matching exported function
for part in "${@}"; do
    ((arg=arg+1))
    tst="${tst}_${part}"
    if [ "" != "$(which $tst)" ] && [ "${#cmd}" -lt "${#tst}" ]; then
        shift_to=$arg
        cmd=$tst
        found=1
    fi
done

# execute matching function, else execute the default command
if [ "1" = "$found" ]; then
    #echo "executing middleware '$cmd'"
    #echo "executing middleware '$(echo $1 $2 ${@:$shift_to})'"
    $(echo $cmd ${@:$shift_to})
else
    /usr/bin/env $1 "${@:2}"
fi
