#!/usr/bin/env bash

# add 'ls' to the current list of custom commands
export __go_commands="${__go_commands} vendor"

#
# List all files tracked by go
#
function go-vendor {
    go mod download -x && go mod tidy -v && go mod vendor
}
