#!/usr/bin/env bash

alias a="cal"
alias automagicproxy="docker stop automagicproxy && docker rm -f automagicproxy && docker pull kcmerrill/automagicproxy && docker run -d -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock --restart=always --name automagicproxy kcmerrill/automagicproxy --dockerized --containerized --dev"
alias busy='while [ TRUE ]; do head -n 100 /dev/urandom; sleep .05; done | hexdump -C | grep --color=none "ca fe"'
alias cloc="perl ~/cloc.pl"
alias cls='clear'
alias cp='cp -i'
alias csl='clear'
alias e='exit'
alias ed="emacs"
alias em="emacs"
alias grep='grep --color=auto'
alias ivm='vim'
alias l='ls -1'
alias lcs='clear'
alias less='less -R'
alias ll='ls -l'
alias locate='locate -i'
alias ls='ls gls -aF --time-style=+"%a %Y-%m-%d %T" --color=auto'
alias more='less'
alias mv='mv -i'
alias rm='rm -i'
alias pcio='nano'
alias pcoi='nano'
alias pico='nano'
alias pioc='nano'
alias pstree='pstree -ahlpuU'
alias rsync='rsync --progress'
alias sqlplus="rlwrap -i -f ~/.sqlplus_history -H ~/.sqlplus_history -s 30000 sqlplus"
alias sqlplus64="rlwrap -i -f ~/.sqlplus_history -H ~/.sqlplus_history -s 30000 sqlplus64"
alias suod='sudo'
alias top='htop -d 5'
alias vi='vim'
alias yes="echo no"

#
# Platform specific aliases
#
platform=`uname`
if [[ $platform == 'Linux' ]]; then
    echo "nothing to override" > /dev/null

elif [[ $platform == 'Darwin' ]]; then
    if [ -f "/Applications/MacVim.app/Contents/MacOS/Vim" ]; then
        alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
    fi

    # brew install coreutils
    if [ -f "/usr/local/bin/gls" ]; then
        eval $(gdircolors)
        alias ls='gls -aF --time-style=+"%a %Y-%m-%d %T" --color=auto'

    # os x native, doesn't show broken symlinks
    else
        export LSCOLORS=ExGxcxdxcxegedcbcdacad # http://www.marinamele.com/2014/05/customize-colors-of-your-terminal-in-mac-os-x.html
        alias ls='ls -aFG'
    fi

elif [[ $platform == 'SunOS' ]]; then
   export TERM=vt100
   alias ls='ls -aF'
fi
