#!/usr/bin/env bash

# k8s status line
# Displays a UTF-8 icon and the current kubectl context and namespace:
# ⎈ docker-for-desktop/default
export K8S_PS1_SYMBOL=$'\xE2\x8E\x88'

__k8s_status() {
    if [ "enabled" = "$K8S_STATUS_LINE" ]; then
        kx=$(basename $(kx) 2> /dev/null)
        if [ "" != "$kx" ]; then
            echo "${__K8S_PS1_SYMBOL}${kx}:$(kn)"
        fi
    fi
}
