#!/usr/bin/env bash

function fetchproxy() {
    docker stop fetch-proxy
    docker rm fetch-proxy
    docker run -d -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock --restart=always --name fetch-proxy -e DOCKER_API_VERSION=1.18 kcmerrill/fetch-proxy --dev --containerized
}

alias a="cal"
alias alien="docker run --rm -t -v $(pwd):/rpm mkenney/alien"
alias busy='while [ TRUE ]; do head -n 100 /dev/urandom; sleep .05; done | hexdump -C | grep --color=none "ca fe"'
alias cloc="perl ~/.dotfiles/cloc.pl"
alias cls='clear'
alias cp='cp -i'
alias csl='clear'
alias dev='devenv'
alias e='exit'
alias ed="emacs"
alias em="emacs"
alias grep='grep --color=auto'
alias iv='vim'
alias ivm='vim'
alias l='ls -1'
alias lcs='clear'
alias less='less -R'
alias ll='ls -l'
alias locate='locate -i'
alias ls='ls -aF --time-style=+"%a %Y-%m-%d %T" --color=auto'
alias more='less'
alias mv='mv -i'
alias pstree='pstree -ahlpuU'
alias rm='rm -i'
alias rsync='rsync --progress'
alias sed='gsed'
alias ssh='$(brew --prefix)/bin/ssh'
alias sourcedot='source ~/.bashrc'
alias sqlplus="rlwrap -i -f ~/.sqlplus_history -H ~/.sqlplus_history -s 30000 sqlplus"
alias sqlplus64="rlwrap -i -f ~/.sqlplus_history -H ~/.sqlplus_history -s 30000 sqlplus64"
alias suod='sudo'
alias top='htop -d 5'
alias vi='vim'
alias yes="echo no"

#
# Platform specific aliases
#
platform=`uname`
if [[ $platform == 'Linux' ]]; then
    echo "nothing to override" > /dev/null

elif [[ $platform == 'Darwin' ]]; then
    if [ -f "/Applications/MacVim.app/Contents/MacOS/Vim" ]; then
        alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
        alias vimdiff='/Applications/MacVim.app/Contents/bin/vimdiff'
    fi

    # `brew install coreutils` to get gls
    if [ -f "$(brew --prefix)/bin/gls" ]; then
        alias ls='gls -aF --time-style=+"%a %Y-%m-%d %T" --color=auto'
        alias realpath='grealpath'

    # bash 3 (os x default...). fails to show broken symlinks
    else
        alias ls='ls -aFG'
    fi

elif [[ $platform == 'SunOS' ]]; then
   alias ls='ls -aF'
fi
