#!/bin/bash

alias a="aquaduck"
alias aws-eo="$(aquaduck aws -p eo)"

auth() {
    $(aquaduck aws -p eo)
    case "$1" in
        "test"|"prod")
            aquaduck auth ssh -e eo-${1}
            aquaduck auth kube -l eo-${1}
        ;;
        "docker")
            aws ecr get-login --no-include-email \
                | awk '{print $6}' \
                | docker login \
                    -u AWS \
                    --password-stdin \
                    $(aws ecr get-authorization-token --output text --query 'authorizationData[].proxyEndpoint')
        ;;
        "")
            echo "you must specify an environment"
            exit 2
        ;;
        *)
            echo "invalid environment '$1'"
            exit 3
        ;;
    esac
}
