#!/bin/bash

alias a="aquaduck"

#
# auth aws - authenticate into aws. needed for aws-cli and kubctl commands.
# auth [eo-test|eo-prod] - create SSH keys and update your KUBECONFIG.
# auth docker - authenticate docker for access to ECR images.
#
auth() {
    case "$1" in
        "aws")
            $(aquaduck aws -p eo)
        ;;
        "eo-test"|"eo-prod")
            aquaduck auth ssh -e ${1}
            if [ -f "$HOME/.kube/$1/config" ]; then
                eval "export __LAST_KUBECONFIG=$KUBECONFIG"
                eval "export KUBECONFIG=$HOME/.kube/$1/config"
            elif [ -f "$HOME/.kube/$1/config.kops" ]; then
                eval "export __LAST_KUBECONFIG=$KUBECONFIG"
                eval "export KUBECONFIG=$HOME/.kube/$1/config.kops"
            else
                >&2 echo "File not found: $HOME/.kube/$1/config"
            fi
        ;;
        "docker")
            $(aquaduck aws -p eo)
            aws ecr get-login --no-include-email \
                | awk '{print $6}' \
                | docker login \
                    -u AWS \
                    --password-stdin \
                    $(aws ecr get-authorization-token --output text --region us-east-1 --query 'authorizationData[].proxyEndpoint')
        ;;
        "")
            echo "you must specify an environment"
        ;;
        *)
            echo "invalid environment '$1'"
        ;;
    esac
}
