#!/bin/bash

alias a="aquaduck"
alias aws-eo="$(aquaduck aws -p eo)"

auth() {
    $(aquaduck aws -p eo)
    case "$1" in
        "eo-test"|"eo-prod")
            aquaduck auth ssh -e ${1}
            aquaduck auth kube ${1} > /dev/null
            export KUBECONFIG=$HOME/.kube/$1/config.vault:$HOME/.kube/$1/config
        ;;
        "docker")
            aws ecr get-login --no-include-email \
                | awk '{print $6}' \
                | docker login \
                    -u AWS \
                    --password-stdin \
                    $(aws ecr get-authorization-token --output text --query 'authorizationData[].proxyEndpoint')
        ;;
        "")
            echo "you must specify an environment"
        ;;
        *)
            echo "invalid environment '$1'"
        ;;
    esac
}
