#!/usr/bin/env bash

# AWS test
alias kt="KUBECONFIG=$HOME/.kube/test/config kubectl"

# AWS prod
alias kp="KUBECONFIG=$HOME/.kube/prod/config kubectl"

# SG test
alias kst="KUBECONFIG=$HOME/.kube/kubesgtest/config kubectl"

# SG prod
alias ksp="KUBECONFIG=$HOME/.kube/kubesgprod/config kubectl"
