#!/usr/bin/env bash

function __ext_kubectl_get {
    if [ "$1" == "all" ]; then
        /usr/bin/env kubectl get namespace,replicaset,secret,job,daemonset,statefulset,ingress,configmap,pv,pvc,service,deployment,pod,nodes
    else
        /usr/bin/env kubectl get "${@:1}"
    fi
}
