#!/usr/bin/env zsh

#
# Gerrit-specific aliases and functions
#

# Auto-clean common coding style errors
#export GIT_PRECH_CLEANALL=true

# Don't let phpcs errors block commits
#export GIT_PRECH_ALWAYSCOMMIT=true

#unalias vimdiff_wrapper='vimdiff "$2" "$5"'

#
# List of custom commands, space delimited.  This var should be
# updated by your resources/lib/[git-command] file
#
export git_custom_commands=""

#
# Return the list of custom commands.  This is also used for tab-completion
#
_git_autocomplete_commands() {
	echo "${git_custom_commands}"
}

#
# Load all of the custom commands in resources/lib/.  These must be prefixed with 'git-'
#
for git_lib in $(find ${HOME}/.dotfiles/zsh/lib/git-* -maxdepth 1 -not -type d -and -not -name '.*'); do
	. $git_lib
done

#
# git command wrapper + alias
#
_git_better() {
	custom_commands="$(_git_autocomplete_commands)"
	for a in ${custom_commands[@]}
	do
		if [ "${1}" = "${a}" ]; then
			"git-$a" "${@:2}"
			return
		fi
	done

	/usr/bin/env git "$@"

}

alias git='_git_better'
