#!/usr/bin/env bash

platform=`uname`
if [[ $platform == 'Linux' ]]; then

    # enable pathname expansion
    shopt -s direxpand

    # disable spelling correction
    shopt -u dirspell
fi

# include dotfiles in filename expansion
shopt -s dotglob

# enable alias name expansion
shopt -s expand_aliases

# enable extended pattern matching: http://en.chys.info/2009/02/extglob/
shopt -s nocaseglob

# Case-insensitive auto-completion
#set completion-ignore-case On

# Tab completion for sudo
complete -cf sudo

# Tab completion for which
complete -cf which

# Tab completion for man
complete -cf man
