#!/usr/bin/env bash

# List of custom commands, space delimited.  This var should be
# updated by your bash/lib/[go-command] file
export __go_commands=""

# Return the list of custom commands.  This is also used for
# tab-completion
__go_autocomplete_commands() {
    echo "${__go_commands}"
}
export -f __go_autocomplete_commands

# Load all of the custom commands in resources/lib/.  These must be
# prefixed with 'go-'
for go_lib in $(find ${HOME}/.dotfiles/bash/lib/go-* -maxdepth 1 -not -type d -and -not -name '.*'); do
    source $go_lib
done

# go command wrapper + alias
#   Executes any custom commands found in the ./lib directory and
#   displays an interactive menu for "did you mean" error suggestions.
__go_better() {
    # Execute any command wrappers or extensions.
    custom_commands="$__go_commands"
    custom_command_executed=0
    for a in ${custom_commands[@]}; do
        if [ "$1" = "$a" ]; then
            $(echo "go-$a" "${@:2}")
            custom_command_executed=1
            break
        fi
    done

    if [ 0 -eq $custom_command_executed ]; then
        /usr/bin/env go "$@"
    fi
}

export -f __go_better
alias go='__go_better'
