#!/usr/bin/env bash

__k8s_status() {
    if [ "enabled" = "$K8S_STATUS_LINE" ]; then
        printf "$(kctx)$(kns)"
    fi
}
export -f __k8s_status

kprompt() {
    if [ "" == "$1" ]; then
        echo $K8S_STATUS_LINE
    elif [ "off" != "$1" ]; then
        eval 'export K8S_STATUS_LINE=enabled'
    else
        eval 'export K8S_STATUS_LINE=disabled'
    fi
}
export -f kprompt
export K8S_STATUS_LINE=enabled
