#!/usr/bin/env bash

__k8s_status() {
    if ((BASH_VERSINFO[0] >= 4)) && [[ $'\u2388 ' != "\\u2388 " ]]; then
        KUBE_PS1_SYMBOL="k8s"
    else
        KUBE_PS1_SYMBOL=$'\xE2\x8E\x88'
    fi
    if [ "enabled" = "$K8S_STATUS_LINE" ]; then
        printf "${KUBE_PS1_SYMBOL} $(kctx)$(kns)"
    fi
}
export -f __k8s_status

kprompt() {
    if [ "" == "$1" ]; then
        echo $K8S_STATUS_LINE
    elif [ "off" != "$1" ]; then
        eval 'export K8S_STATUS_LINE=enabled'
    else
        eval 'export K8S_STATUS_LINE=disabled'
    fi
}
export -f kprompt
export K8S_STATUS_LINE=enabled


