#!/usr/bin/env bash

#
# Set the bash prompt
# https://wiki.archlinux.org/index.php/Color_Bash_Prompt
#

# Load color definitions
source ~/.dotfiles/common/color

__prompt_command() {
    # always first to capture the last shell error
    local last_status=$?

    local -a ps1_lines

    # Line 1 - host and current path
    if [ "$EUID" = "0" ]; then
        # Root
        ps1_lines+='\n┌\[${COLOR_RED_BLINK}\]\u\[\e[0m\]\[${COLOR_YELLOW_FADED}\]@\H\[${COLOR_NORM}\] - \[${COLOR_NORM_FADED}\]$PWD\[${COLOR_NORM}\]'
    else
        ps1_lines+='\n┌\[${COLOR_YELLOW_FADED}\]\u@\H\[${COLOR_NORM}\] - \[${COLOR_NORM_FADED}\]$PWD\[${COLOR_NORM}\]'
    fi

    # Line 2 - k8s status line
    if [ "enabled" = "$K8S_STATUS_LINE" ]; then
        ps1_lines+='\n│\[${COLOR_DKGREEN_FADED}\]$(__k8s_status)\[${COLOR_NORM}\] '
    fi

    # Line 3 - git status line
    in_git_repo=$(git rev-parse --is-inside-work-tree 2> /dev/null)
    if [ "true" = "$in_git_repo" ]; then # In a git repo
        ps1_lines+='\n│\[${COLOR_BLUE_FADED}\]$(__git_status)\[${COLOR_NORM}\] '
    fi

    # Line 4 - time and error state
    if [ "0" == "$last_status" ] || [ "" == "$last_status" ]; then
        # no current error code
        ps1_lines+='\n└\[${COLOR_GREEN_FADED}\]\t\[${COLOR_NORM}\] → '
    else
        # last script exited with a non-zero code
        ps1_lines+="\n└\[${COLOR_GREEN_FADED}\]\t\[${COLOR_NORM}\] (\[${COLOR_RED_FADED}\]$last_status\[${COLOR_NORM}\]) ⤳ "
    fi

    # Make the cursor a blinking vertical line
    # http://stackoverflow.com/questions/4416909/anyway-change-the-cursor-vertical-line-instead-of-a-box
    ps1_lines+=$(echo -e -n "\[\x1b[\x35 q\]")

    PS1="${ps1_lines[*]}"
}
export PROMPT_COMMAND=__prompt_command

export PS2='\[${COLOR_NORM_BOLD}\]\>\[${COLOR_NORM}\] '
